services:
  embedapi:
    build:
      context: ./embed
      dockerfile: Dockerfile
    environment:
      - HF_HOME=/app/huggingface_cache
    volumes:
      - ./docker/huggingface_cache:/app/huggingface_cache
    
  translateapi:
    build:
      context: ./translate
      dockerfile: Dockerfile
    environment:
      - XDG_CACHE_HOME=/app/argos_cache
    volumes:
      - ./docker/argos_cache:/app/argos_cache

  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/database:/docker-entrypoint-initdb.d

  serviceapi:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    depends_on:
      - embedapi
      - translateapi
      - db
    environment:
      - EMBEDDING_URL=embedapi:50051
      - TRANSLATE_URL=translateapi:50051
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

volumes:
  db_data: