// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: translate.proto

package translate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the text to be translated and language details.
type TranslationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Text           string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                           // The text to be translated.
	SourceLanguage string                 `protobuf:"bytes,2,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"` // The source language code (e.g., "en").
	TargetLanguage string                 `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"` // The target language code (e.g., "es").
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranslationRequest) Reset() {
	*x = TranslationRequest{}
	mi := &file_translate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationRequest) ProtoMessage() {}

func (x *TranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationRequest.ProtoReflect.Descriptor instead.
func (*TranslationRequest) Descriptor() ([]byte, []int) {
	return file_translate_proto_rawDescGZIP(), []int{0}
}

func (x *TranslationRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationRequest) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *TranslationRequest) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

// The response message containing the translated text.
type TranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Translation   string                 `protobuf:"bytes,1,opt,name=translation,proto3" json:"translation,omitempty"` // The translated text.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationResponse) Reset() {
	*x = TranslationResponse{}
	mi := &file_translate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationResponse) ProtoMessage() {}

func (x *TranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationResponse.ProtoReflect.Descriptor instead.
func (*TranslationResponse) Descriptor() ([]byte, []int) {
	return file_translate_proto_rawDescGZIP(), []int{1}
}

func (x *TranslationResponse) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

var File_translate_proto protoreflect.FileDescriptor

const file_translate_proto_rawDesc = "" +
	"\n" +
	"\x0ftranslate.proto\x12\ttranslate\"z\n" +
	"\x12TranslationRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12'\n" +
	"\x0fsource_language\x18\x02 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\"7\n" +
	"\x13TranslationResponse\x12 \n" +
	"\vtranslation\x18\x01 \x01(\tR\vtranslation2X\n" +
	"\n" +
	"Translator\x12J\n" +
	"\tTranslate\x12\x1d.translate.TranslationRequest\x1a\x1e.translate.TranslationResponseB#Z!translationsapi/service;translateb\x06proto3"

var (
	file_translate_proto_rawDescOnce sync.Once
	file_translate_proto_rawDescData []byte
)

func file_translate_proto_rawDescGZIP() []byte {
	file_translate_proto_rawDescOnce.Do(func() {
		file_translate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translate_proto_rawDesc), len(file_translate_proto_rawDesc)))
	})
	return file_translate_proto_rawDescData
}

var file_translate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_translate_proto_goTypes = []any{
	(*TranslationRequest)(nil),  // 0: translate.TranslationRequest
	(*TranslationResponse)(nil), // 1: translate.TranslationResponse
}
var file_translate_proto_depIdxs = []int32{
	0, // 0: translate.Translator.Translate:input_type -> translate.TranslationRequest
	1, // 1: translate.Translator.Translate:output_type -> translate.TranslationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translate_proto_init() }
func file_translate_proto_init() {
	if File_translate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translate_proto_rawDesc), len(file_translate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translate_proto_goTypes,
		DependencyIndexes: file_translate_proto_depIdxs,
		MessageInfos:      file_translate_proto_msgTypes,
	}.Build()
	File_translate_proto = out.File
	file_translate_proto_goTypes = nil
	file_translate_proto_depIdxs = nil
}
